version: "3"

services:
    nginx:
        image: ghcr.io/nuclearsheep540/rollplay/nginx:0.0.2
        build:
            context: ./docker/prod/nginx
            dockerfile: Dockerfile
        container_name: nginx
        ports:
          - "80:80"
          - "443:443"
        restart: unless-stopped
    api:
        hostname: api
        stdin_open: true
        tty: true
        env_file:
            - .env
        container_name: "api"
        image: ghcr.io/nuclearsheep540/rollplay/api:0.0.1
        build:
            context: ./api
            dockerfile: ../docker/prod/api/Dockerfile
        ports: 
            - 8081:8081
    rollplay:
        stdin_open: true
        tty: true
        env_file:
            - .env
        container_name: "rollplay"
        image: ghcr.io/nuclearsheep540/rollplay/rollplay:0.0.1
        build:
            context: ./rollplay
            dockerfile: ../docker/prod/rollplay/Dockerfile
        ports:
        - "3000:3000"
    db:
        stdin_open: true
        tty: true
        restart: always
        env_file:
            - .env
        container_name: "db"
        hostname: mongo
        image: ghcr.io/nuclearsheep540/rollplay/db:0.0.1
        build:
            context: ./docker
            dockerfile: prod/db/Dockerfile
        ports:
        - "27017:27017"

networks:
  default:
    driver: bridge
