"""Fix cascade delete for game_joined_users

Revision ID: 6c21e83c0f21
Revises: 88752d81f9e6
Create Date: 2025-11-18 18:36:45.074334

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c21e83c0f21'
down_revision = '88752d81f9e6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_friend_requests_recipient', table_name='friend_requests')
    op.drop_index('idx_friend_requests_requester', table_name='friend_requests')
    op.drop_table('friend_requests')
    op.drop_index('idx_friendships_user1', table_name='friendships')
    op.drop_index('idx_friendships_user2', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user1_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user2_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('user1_id < user2_id', name='ordered_friendship'),
    sa.CheckConstraint('user1_id <> user2_id', name='no_self_friendship_new'),
    sa.ForeignKeyConstraint(['user1_id'], ['users.id'], name='friendships_new_user1_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user2_id'], ['users.id'], name='friendships_new_user2_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='friendships_new_pkey'),
    sa.UniqueConstraint('user1_id', 'user2_id', name='uq_friendships_user1_user2')
    )
    op.create_index('idx_friendships_user2', 'friendships', ['user2_id'], unique=False)
    op.create_index('idx_friendships_user1', 'friendships', ['user1_id'], unique=False)
    op.create_table('friend_requests',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('requester_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('requester_id <> recipient_id', name='no_self_request'),
    sa.ForeignKeyConstraint(['recipient_id'], ['users.id'], name='friend_requests_recipient_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], name='friend_requests_requester_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='friend_requests_pkey'),
    sa.UniqueConstraint('requester_id', 'recipient_id', name='uq_friend_requests_requester_recipient')
    )
    op.create_index('idx_friend_requests_requester', 'friend_requests', ['requester_id', sa.text('created_at DESC')], unique=False)
    op.create_index('idx_friend_requests_recipient', 'friend_requests', ['recipient_id', sa.text('created_at DESC')], unique=False)
    # ### end Alembic commands ###