"""add fog_config to map_assets

Revision ID: 0bd65054c91c
Revises: 28f84db94841
Create Date: 2026-04-27 17:37:36.884701

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '0bd65054c91c'
down_revision = '28f84db94841'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_assets', sa.Column('fog_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_assets', 'fog_config')
    # ### end Alembic commands ###