"""set null character campaign fk on delete

Revision ID: 0c40c9196357
Revises: 77d7f1fb5678
Create Date: 2026-04-01 16:48:18.347204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c40c9196357'
down_revision = '77d7f1fb5678'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('characters_active_in_campaign_id_fkey', 'characters', type_='foreignkey')
    op.create_foreign_key(None, 'characters', 'campaigns', ['active_in_campaign_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.create_foreign_key('characters_active_in_campaign_id_fkey', 'characters', 'campaigns', ['active_in_campaign_id'], ['id'])
    # ### end Alembic commands ###