"""add loop_start loop_end bpm loop_mode to music_assets

Revision ID: 1525d44a6c92
Revises: 810737a39195
Create Date: 2026-04-04 16:54:22.638340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1525d44a6c92'
down_revision = '810737a39195'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_assets', sa.Column('loop_start', sa.Float(), nullable=True))
    op.add_column('music_assets', sa.Column('loop_end', sa.Float(), nullable=True))
    op.add_column('music_assets', sa.Column('bpm', sa.Float(), nullable=True))
    op.add_column('music_assets', sa.Column('loop_mode', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_assets', 'loop_mode')
    op.drop_column('music_assets', 'bpm')
    op.drop_column('music_assets', 'loop_end')
    op.drop_column('music_assets', 'loop_start')
    # ### end Alembic commands ###