"""add friend codes table

Revision ID: 15637668dd0b
Revises: 2e78d14b0423
Create Date: 2025-11-28 16:01:26.311720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '15637668dd0b'
down_revision = '2e78d14b0423'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friend_codes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('friend_code', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_index(op.f('ix_friend_codes_friend_code'), 'friend_codes', ['friend_code'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_friend_codes_friend_code'), table_name='friend_codes')
    op.drop_table('friend_codes')
    # ### end Alembic commands ###