"""add exhaustion_level

Revision ID: 194886c40690
Revises: beb9ee0c6021
Create Date: 2026-07-05 18:42:31.626737

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '194886c40690'
down_revision = 'beb9ee0c6021'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('exhaustion_level', sa.SmallInteger(), server_default='0', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'exhaustion_level')
    # ### end Alembic commands ###