"""skills projection: add class_entries.chosen_skills, drop skill.granted_by

Revision ID: 1ae44390c2e0
Revises: 98a3f6e6f5e4
Create Date: 2026-07-06 10:02:59.389490

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ae44390c2e0'
down_revision = '98a3f6e6f5e4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_class_entries', sa.Column('chosen_skills', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    op.drop_column('character_skill_proficiencies', 'granted_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_skill_proficiencies', sa.Column('granted_by', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False))
    op.drop_column('character_class_entries', 'chosen_skills')
    # ### end Alembic commands ###