"""Add image_config and active_display to sessions

Revision ID: 21f48b989699
Revises: 8fae6a249f4e
Create Date: 2026-02-18 20:55:39.338986

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '21f48b989699'
down_revision = '8fae6a249f4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('image_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    op.add_column('sessions', sa.Column('active_display', sa.String(length=10), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'active_display')
    op.drop_column('sessions', 'image_config')
    # ### end Alembic commands ###