"""add image_assets joined table for display config

Revision ID: 24351b802614
Revises: aade28b58b90
Create Date: 2026-03-31 17:58:10.716266

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24351b802614'
down_revision = 'aade28b58b90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('display_mode', sa.String(length=20), nullable=True),
    sa.Column('aspect_ratio', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Backfill: create joined-table rows for existing IMAGE assets
    op.execute(
        "INSERT INTO image_assets (id) "
        "SELECT id FROM media_assets WHERE asset_type = 'image' "
        "AND id NOT IN (SELECT id FROM image_assets)"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('image_assets')
    # ### end Alembic commands ###