"""add time_signature to music_assets

Revision ID: 28f84db94841
Revises: a894be58c9d4
Create Date: 2026-04-20 22:41:58.933324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28f84db94841'
down_revision = 'a894be58c9d4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_assets', sa.Column('time_signature', sa.String(length=8), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_assets', 'time_signature')
    # ### end Alembic commands ###