"""drop session active_game_id

Revision ID: 295bcace5419
Revises: 5d79a91d9d41
Create Date: 2026-08-29 23:51:21.497318

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '295bcace5419'
down_revision = '5d79a91d9d41'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'active_game_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('active_game_id', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    # ### end Alembic commands ###