"""add hero_image_asset_id to campaigns

Revision ID: 302ffa113c36
Revises: 0c40c9196357
Create Date: 2026-04-02 16:11:25.945436

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '302ffa113c36'
down_revision = '0c40c9196357'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('hero_image_asset_id', sa.UUID(), nullable=True))
    op.create_foreign_key(None, 'campaigns', 'media_assets', ['hero_image_asset_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'campaigns', type_='foreignkey')
    op.drop_column('campaigns', 'hero_image_asset_id')
    # ### end Alembic commands ###