"""add focal_areas to image_assets

Revision ID: 363689ff031b
Revises: 5dd65cb9eb92
Create Date: 2026-07-23 20:04:07.281236

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '363689ff031b'
down_revision = '5dd65cb9eb92'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('focal_areas', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_assets', 'focal_areas')
    # ### end Alembic commands ###