"""add effect toggle columns to music assets

Revision ID: 37b44a754c71
Revises: e724fd0bd585
Create Date: 2026-02-23 09:51:45.423085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37b44a754c71'
down_revision = 'e724fd0bd585'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_assets', sa.Column('effect_hpf_enabled', sa.Boolean(), nullable=True))
    op.add_column('music_assets', sa.Column('effect_lpf_enabled', sa.Boolean(), nullable=True))
    op.add_column('music_assets', sa.Column('effect_reverb_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_assets', 'effect_reverb_enabled')
    op.drop_column('music_assets', 'effect_lpf_enabled')
    op.drop_column('music_assets', 'effect_hpf_enabled')
    # ### end Alembic commands ###