"""add token_config to map_assets

Revision ID: 38ca400aa994
Revises: 592caea6c36a
Create Date: 2026-07-23 19:50:33.797789

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '38ca400aa994'
down_revision = '592caea6c36a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_assets', sa.Column('token_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_assets', 'token_config')
    # ### end Alembic commands ###