"""add friendship model

Revision ID: 38d3d2f42f52
Revises: 709fffa9301e
Create Date: 2025-07-15 10:20:03.970872

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38d3d2f42f52'
down_revision = '709fffa9301e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('requester_id', sa.UUID(), nullable=False),
    sa.Column('addressee_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['addressee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['requester_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_friendship_requester_addressee', 'friendships', ['requester_id', 'addressee_id'], unique=False)
    op.create_index('ix_friendship_status', 'friendships', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_friendship_status', table_name='friendships')
    op.drop_index('ix_friendship_requester_addressee', table_name='friendships')
    op.drop_table('friendships')
    # ### end Alembic commands ###