"""add user last_seen for presence grace window

Revision ID: 4095d1fcc9a0
Revises: a8e1bf630345
Create Date: 2026-08-31 11:49:51.317702

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4095d1fcc9a0'
down_revision = 'a8e1bf630345'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_seen', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_seen')
    # ### end Alembic commands ###