"""add ability_score_method and ability_roll_details to characters

Revision ID: 5d15be3a6c72
Revises: bb56388d8044
Create Date: 2026-05-27 12:21:43.931015

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5d15be3a6c72'
down_revision = 'bb56388d8044'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('ability_score_method', sa.String(length=20), nullable=True))
    op.add_column('characters', sa.Column('ability_roll_details', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'ability_roll_details')
    op.drop_column('characters', 'ability_score_method')
    # ### end Alembic commands ###