"""add audio_assets joined table for music and sfx

Revision ID: 5db7a22fb5c6
Revises: 21f48b989699
Create Date: 2026-02-19 14:49:40.340065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5db7a22fb5c6'
down_revision = '21f48b989699'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('default_volume', sa.Float(), nullable=True),
    sa.Column('default_looping', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###

    # Data migration: create audio_assets rows for existing MUSIC/SFX assets
    op.execute(
        "INSERT INTO audio_assets (id) "
        "SELECT id FROM media_assets WHERE asset_type IN ('music', 'sfx')"
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_assets')
    # ### end Alembic commands ###