"""add map_token_seed to sessions

Revision ID: 5dd65cb9eb92
Revises: 38ca400aa994
Create Date: 2026-07-23 19:59:48.180865

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '5dd65cb9eb92'
down_revision = '38ca400aa994'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('map_token_seed', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'map_token_seed')
    # ### end Alembic commands ###