"""add_mongodb_session_id_to_games

Revision ID: 639729e8481f
Revises: a226784c53db
Create Date: 2025-07-18 13:26:45.125326

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '639729e8481f'
down_revision = 'a226784c53db'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('campaigns', 'updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_campaigns_dm_id', table_name='campaigns')
    op.drop_column('campaigns', 'maps')
    op.add_column('games', sa.Column('mongodb_session_id', sa.String(), nullable=True))
    op.alter_column('games', 'combat_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('games', 'total_play_time',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text('0'))
    op.alter_column('games', 'started_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.alter_column('games', 'ended_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True)
    op.drop_index('idx_games_campaign_id', table_name='games')
    op.drop_index('idx_games_status', table_name='games')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_games_status', 'games', ['status'], unique=False)
    op.create_index('idx_games_campaign_id', 'games', ['campaign_id'], unique=False)
    op.alter_column('games', 'ended_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('games', 'started_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('games', 'total_play_time',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text('0'))
    op.alter_column('games', 'combat_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_column('games', 'mongodb_session_id')
    op.add_column('campaigns', sa.Column('maps', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.create_index('idx_campaigns_dm_id', 'campaigns', ['dm_id'], unique=False)
    op.alter_column('campaigns', 'updated_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True)
    op.alter_column('campaigns', 'is_deleted',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    # ### end Alembic commands ###