"""add eq bypass, effect mix levels, and reverb preset to music assets

Revision ID: 6b54f5f634ee
Revises: 638ec6564fb6
Create Date: 2026-03-13 15:55:32.928081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b54f5f634ee'
down_revision = '638ec6564fb6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('music_assets', sa.Column('effect_eq_enabled', sa.Boolean(), nullable=True))
    op.add_column('music_assets', sa.Column('effect_hpf_mix', sa.Float(), nullable=True))
    op.add_column('music_assets', sa.Column('effect_lpf_mix', sa.Float(), nullable=True))
    op.add_column('music_assets', sa.Column('effect_reverb_mix', sa.Float(), nullable=True))
    op.add_column('music_assets', sa.Column('effect_reverb_preset', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('music_assets', 'effect_reverb_preset')
    op.drop_column('music_assets', 'effect_reverb_mix')
    op.drop_column('music_assets', 'effect_lpf_mix')
    op.drop_column('music_assets', 'effect_hpf_mix')
    op.drop_column('music_assets', 'effect_eq_enabled')
    # ### end Alembic commands ###