"""drop dead campaign columns and asset session_ids

Revision ID: 6c2e3c2ce373
Revises: 37b44a754c71
Create Date: 2026-03-10 13:10:55.277317

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6c2e3c2ce373'
down_revision = '37b44a754c71'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'npc_factory')
    op.drop_column('campaigns', 'assets')
    op.drop_column('campaigns', 'scenes')
    op.drop_column('media_assets', 'session_ids')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('session_ids', postgresql.ARRAY(sa.UUID()), server_default=sa.text("'{}'::uuid[]"), autoincrement=False, nullable=False))
    op.add_column('campaigns', sa.Column('scenes', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('assets', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('campaigns', sa.Column('npc_factory', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    # ### end Alembic commands ###