"""add temp_game_ids to users

Revision ID: 709fffa9301e
Revises: a0a9ce17ef6c
Create Date: 2025-07-15 10:10:59.191940

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '709fffa9301e'
down_revision = 'a0a9ce17ef6c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('temp_game_ids', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'temp_game_ids')
    # ### end Alembic commands ###