"""adding character race column

Revision ID: 7247e5460b45
Revises: 8b90c761456a
Create Date: 2025-09-24 12:51:11.442539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7247e5460b45'
down_revision = '8b90c761456a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('character_race', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'character_race')
    # ### end Alembic commands ###