"""add image_position_x_y to image_assets

Revision ID: 77d7f1fb5678
Revises: ef0775587e39
Create Date: 2026-03-31 20:24:19.940756

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '77d7f1fb5678'
down_revision = 'ef0775587e39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('image_position_x', sa.Float(), nullable=True))
    op.add_column('image_assets', sa.Column('image_position_y', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_assets', 'image_position_y')
    op.drop_column('image_assets', 'image_position_x')
    # ### end Alembic commands ###