"""game aggregate: games table owns status and play state

Revision ID: 78e9f165d016
Revises: b1ae5a5e538b
Create Date: 2026-09-06 19:28:38.064218

The session was carrying the game's status and the game's state. Only two
commands ever wrote those columns — start and the take-down — and both are
operations on a game. This moves them onto a `games` table, one row per play,
whose id IS the api-game room id.

Schema changes are autogenerated; the precondition and the data step around them
are hand-authored, and their ORDER matters:

1. REFUSE if any session is not 'inactive'. A live session's MongoDB room is
   keyed by the SESSION id, which no game row will ever match — so a running
   game cannot survive this migration. End every game before deploying.

2. Create `games`, and add `sessions.next_game_name` (empty: nothing was planned
   under the old model).

3. BEFORE the drops, because it reads the columns being dropped: give every
   session that was ever PLAYED one ENDED game carrying its state and its real
   timestamps. This is what keeps continuity alive across the deploy — without
   it the first Start after this migration seeds from nothing and strands the
   players' token positions, which is exactly the bug the one-session model was
   introduced to fix.

   "Played" means it has a started_at or any non-default state. A session that
   was created and never used gets no game: inventing one would put a night in
   the history that never happened.

4. Drop the twelve columns from `sessions`.

Downgrade restores the columns and copies each session's newest ended game's
state and timestamps back onto it, then drops `games`. It can only restore the
NEWEST game per session — older history has no representation on the old shape.
"""
import uuid

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '78e9f165d016'
down_revision = 'b1ae5a5e538b'
branch_labels = None
depends_on = None


# The state columns, in the order both the carry-forward and the restore use them.
# Split by type because psycopg2 cannot adapt a bare Python dict: the JSONB ones
# must be bound with an explicit type or the INSERT fails on the first row that
# actually holds state — which is every row this step exists for.
JSONB_STATE_COLUMNS = (
    'map_token_seed',
    'map_token_state',
    'adventure_log',
    'map_config',
    'image_config',
    'audio_config',
    'spotify_config',
)
STATE_COLUMNS = JSONB_STATE_COLUMNS + ('active_display',)


def _refuse_while_anything_is_running(connection) -> None:
    """Step 1 — a live session cannot cross this migration.

    Its hot room in api-game is keyed by the session id, and after this every
    room is keyed by a game id. There is no mapping that could rescue it, so the
    migration refuses rather than silently orphaning a game people are playing.
    """
    running = connection.execute(
        sa.text("SELECT count(*) FROM sessions WHERE status <> 'inactive'")
    ).scalar_one()
    if running:
        raise RuntimeError(
            f"End every running game before migrating: {running} session(s) are not inactive. "
            f"End them from the campaign drawer on the code being replaced "
            f"(or `admin.py pause-all --yes` there), then deploy."
        )


def _carry_played_sessions_into_games(connection) -> None:
    """Step 3 — every session that was played becomes its own first ENDED game.

    Runs BEFORE the column drops because it reads them.
    """
    played = connection.execute(sa.text(f"""
        SELECT id, campaign_id, host_id, created_at, started_at, stopped_at,
               {', '.join(STATE_COLUMNS)}
        FROM sessions
        WHERE started_at IS NOT NULL
           OR map_token_state <> '{{}}'::jsonb
           OR map_token_seed  <> '{{}}'::jsonb
           OR adventure_log   <> '[]'::jsonb
           OR map_config      <> '{{}}'::jsonb
           OR image_config    <> '{{}}'::jsonb
           OR audio_config    <> '{{}}'::jsonb
           OR spotify_config  <> '{{}}'::jsonb
           OR active_display IS NOT NULL
    """)).fetchall()

    insert_game = sa.text(f"""
        INSERT INTO games (
            id, session_id, campaign_id, host_id, status,
            name, created_at, started_at, ended_at, ended_by,
            urls_expire_at, summary, attendance,
            {', '.join(STATE_COLUMNS)}
        ) VALUES (
            :game_id, :session_id, :campaign_id, :host_id, 'ended',
            NULL, :created_at, :started_at, :ended_at, NULL,
            NULL, NULL, '[]',
            {', '.join(':' + column for column in STATE_COLUMNS)}
        )
    """).bindparams(*(
        sa.bindparam(column, type_=postgresql.JSONB) for column in JSONB_STATE_COLUMNS
    ))

    for row in played:
        session = row._mapping
        connection.execute(
            insert_game,
            {
                # Minted in Python, matching the previous migration: the ids
                # are few and this keeps the step readable next to its bindings.
                "game_id": uuid.uuid4(),
                "session_id": session["id"],
                "campaign_id": session["campaign_id"],
                "host_id": session["host_id"],
                # A row with state but no timestamps was still a game that
                # happened; the session's own creation time keeps the
                # "newest ended" ordering defined rather than null.
                "created_at": session["started_at"] or session["created_at"],
                "started_at": session["started_at"],
                "ended_at": session["stopped_at"] or session["started_at"] or session["created_at"],
                **{column: session[column] for column in STATE_COLUMNS},
            },
        )

    print(f"game migration: created {len(played)} ended game(s) from played sessions")


def _restore_newest_game_onto_sessions(connection) -> None:
    """Downgrade helper — put the last game's state back on its session."""
    restored = connection.execute(sa.text(f"""
        UPDATE sessions AS s
        SET started_at = g.started_at,
            stopped_at = g.ended_at,
            {', '.join(f'{column} = g.{column}' for column in STATE_COLUMNS)}
        FROM (
            SELECT DISTINCT ON (session_id) *
            FROM games
            WHERE status = 'ended'
            ORDER BY session_id, ended_at DESC NULLS LAST, created_at DESC
        ) AS g
        WHERE g.session_id = s.id
    """)).rowcount
    print(f"game migration downgrade: restored {restored} session(s) from their newest game")


def upgrade() -> None:
    connection = op.get_bind()

    _refuse_while_anything_is_running(connection)

    op.create_table('games',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('host_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_by', sa.String(length=20), nullable=True),
    sa.Column('urls_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('attendance', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False),
    sa.Column('map_token_seed', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('map_token_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('adventure_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True),
    sa.Column('map_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('image_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('active_display', sa.String(length=10), nullable=True),
    sa.Column('audio_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.Column('spotify_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['host_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_games_campaign_id', 'games', ['campaign_id'], unique=False)
    # The invariant: one OPEN game per session. The partial clause is what lets
    # ended rows accumulate under the same session_id — without it a session
    # could never be played twice.
    op.create_index('ix_games_one_open_per_session', 'games', ['session_id'], unique=True, postgresql_where=sa.text("status <> 'ended'"), sqlite_where=sa.text("status <> 'ended'"))
    op.create_index('ix_games_session_ended', 'games', ['session_id', 'ended_at'], unique=False)
    op.add_column('sessions', sa.Column('next_game_name', sa.String(length=100), nullable=True))

    _carry_played_sessions_into_games(connection)

    op.drop_column('sessions', 'image_config')
    op.drop_column('sessions', 'adventure_log')
    op.drop_column('sessions', 'stopped_at')
    op.drop_column('sessions', 'started_at')
    op.drop_column('sessions', 'audio_config')
    op.drop_column('sessions', 'spotify_config')
    op.drop_column('sessions', 'map_token_seed')
    op.drop_column('sessions', 'active_display')
    op.drop_column('sessions', 'map_config')
    op.drop_column('sessions', 'urls_expire_at')
    op.drop_column('sessions', 'status')
    op.drop_column('sessions', 'map_token_state')


def downgrade() -> None:
    # server_default on status so this runs against populated tables; every
    # session comes back idle, which is true once the games are gone.
    op.add_column('sessions', sa.Column('map_token_state', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('status', sa.VARCHAR(length=20), server_default='inactive', autoincrement=False, nullable=False))
    op.add_column('sessions', sa.Column('urls_expire_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('map_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('active_display', sa.VARCHAR(length=10), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('map_token_seed', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('spotify_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('audio_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('stopped_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('adventure_log', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('image_config', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=True))

    _restore_newest_game_onto_sessions(op.get_bind())

    op.drop_column('sessions', 'next_game_name')
    op.drop_index('ix_games_session_ended', table_name='games')
    op.drop_index('ix_games_one_open_per_session', table_name='games', postgresql_where=sa.text("status <> 'ended'"), sqlite_where=sa.text("status <> 'ended'"))
    op.drop_index('ix_games_campaign_id', table_name='games')
    op.drop_table('games')
