"""Change campaign player_ids from JSON to JSONB

Revision ID: 7b0368fed808
Revises: a69fcd0b2b6b
Create Date: 2025-11-17 16:15:15.468295

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7b0368fed808'
down_revision = 'a69fcd0b2b6b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # ONLY change player_ids from JSON to JSONB - nothing else
    op.alter_column('campaigns', 'player_ids',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert player_ids from JSONB back to JSON
    op.alter_column('campaigns', 'player_ids',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=False,
               existing_server_default=sa.text("'[]'::json"))
    # ### end Alembic commands ###