"""add grid_enabled to map_assets

Revision ID: 7b61ee400257
Revises: a4a712555166
Create Date: 2026-08-19 10:31:23.350353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7b61ee400257'
down_revision = 'a4a712555166'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_assets', sa.Column('grid_enabled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_assets', 'grid_enabled')
    # ### end Alembic commands ###