"""add user pulse events

Revision ID: 7bfb0f207666
Revises: 4095d1fcc9a0
Create Date: 2026-08-31 12:28:25.394922

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '7bfb0f207666'
down_revision = '4095d1fcc9a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('pulse_events', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'pulse_events')
    # ### end Alembic commands ###