"""add character_resource_usage table

Revision ID: 7d6ffc78650a
Revises: e61ec3b03fc6
Create Date: 2026-06-30 11:21:56.558622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7d6ffc78650a'
down_revision = 'e61ec3b03fc6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_resource_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('pool_code', sa.String(length=40), nullable=False),
    sa.Column('current_value', sa.Integer(), server_default='0', nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_resource_usage')
    # ### end Alembic commands ###