"""dissolve cine_config into top-level image config fields

Revision ID: 810737a39195
Revises: 302ffa113c36
Create Date: 2026-04-03 15:35:20.941873

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '810737a39195'
down_revision = '302ffa113c36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('image_fit', sa.String(length=20), nullable=True))
    op.add_column('image_assets', sa.Column('visual_overlays', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('image_assets', sa.Column('motion', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # Backfill image_fit from old display_mode (float/wrap/letterbox were fit values)
    op.execute(sa.text("""
        UPDATE image_assets
        SET image_fit = display_mode
        WHERE display_mode IN ('float', 'wrap', 'letterbox', 'cine')
    """))

    # Coerce legacy 'cine' image_fit to 'letterbox' (cine was always letterbox + hide UI)
    op.execute(sa.text("""
        UPDATE image_assets
        SET image_fit = 'letterbox'
        WHERE image_fit = 'cine'
    """))

    # Coerce display_mode to new standard/cine enum
    op.execute(sa.text("""
        UPDATE image_assets
        SET display_mode = CASE
            WHEN display_mode = 'cine' THEN 'cine'
            ELSE 'standard'
        END
    """))

    # Extract overlays and motion from cine_config before dropping it
    op.execute(sa.text("""
        UPDATE image_assets
        SET visual_overlays = cine_config -> 'visual_overlays',
            motion = cine_config -> 'motion'
        WHERE cine_config IS NOT NULL
    """))

    op.drop_column('image_assets', 'cine_config')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('cine_config', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('image_assets', 'motion')
    op.drop_column('image_assets', 'visual_overlays')
    op.drop_column('image_assets', 'image_fit')
    # ### end Alembic commands ###