"""character slots and user max_slots

Revision ID: 8996438a78f1
Revises: 0d7cc2299014
Create Date: 2026-08-30 18:23:20.530466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8996438a78f1'
down_revision = '0d7cc2299014'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('slot', sa.SmallInteger(), nullable=True))
    op.create_unique_constraint('uq_characters_user_slot', 'characters', ['user_id', 'slot'])
    op.add_column('users', sa.Column('max_slots', sa.Integer(), server_default='4', nullable=False))
    # ### end Alembic commands ###

    # Hand-added: autogenerate does not detect CHECK constraints. These mirror
    # the declarations on the models.
    op.create_check_constraint(
        'ck_characters_slot_range', 'characters', 'slot IS NULL OR (slot >= 0 AND slot < 8)'
    )
    op.create_check_constraint(
        'ck_users_max_slots_range', 'users', 'max_slots >= 1 AND max_slots <= 8'
    )

    # Backfill: number each user's live characters into slots by creation
    # order. Soft-deleted rows keep slot NULL (not occupying capacity).
    # Verified pre-migration: no user holds more than 3 live characters.
    op.execute(
        """
        UPDATE characters
        SET slot = numbered.slot
        FROM (
            SELECT id, ROW_NUMBER() OVER (
                PARTITION BY user_id ORDER BY created_at
            ) - 1 AS slot
            FROM characters
            WHERE is_deleted = false
        ) AS numbered
        WHERE characters.id = numbered.id
        """
    )


def downgrade() -> None:
    op.drop_constraint('ck_users_max_slots_range', 'users', type_='check')
    op.drop_constraint('ck_characters_slot_range', 'characters', type_='check')
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'max_slots')
    op.drop_constraint('uq_characters_user_slot', 'characters', type_='unique')
    op.drop_column('characters', 'slot')
    # ### end Alembic commands ###