"""campaign system name

Revision ID: 8bae7f924a9e
Revises: a0897b4aa764
Create Date: 2026-09-15 08:11:00.491688

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8bae7f924a9e'
down_revision = 'a0897b4aa764'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('system_name', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'system_name')
    # ### end Alembic commands ###