"""add color to users

Revision ID: 8d44e50b786f
Revises: a039537eea9f
Create Date: 2026-07-21 11:54:37.529387

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d44e50b786f'
down_revision = 'a039537eea9f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('color', sa.String(length=7), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'color')
    # ### end Alembic commands ###