"""add_map_assets_table_and_session_map_config

Revision ID: 8fae6a249f4e
Revises: 6c168329e5f0
Create Date: 2026-02-06 13:17:25.353112

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8fae6a249f4e'
down_revision = '6c168329e5f0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('grid_width', sa.Integer(), nullable=True),
    sa.Column('grid_height', sa.Integer(), nullable=True),
    sa.Column('grid_opacity', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    # Migrate existing MAP assets - create map_assets rows with NULL grid values (not yet configured)
    op.execute("""
        INSERT INTO map_assets (id)
        SELECT id FROM media_assets WHERE asset_type = 'map'
    """)

    op.add_column('sessions', sa.Column('map_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'map_config')
    op.drop_table('map_assets')
    # ### end Alembic commands ###