"""one session per campaign: retire FINISHED, seat count to campaign

Revision ID: 9584fb2e1a4c
Revises: 7bfb0f207666
Create Date: 2026-09-06 07:22:37.555895

Schema changes are autogenerated; the data steps around them are hand-authored
and their ORDER matters. Two halves, split by the column drops:

BEFORE the drops (they read sessions.max_players):
1. Backfill campaigns.max_players from the campaign's current session.
2. Delete every FINISHED session. The status is gone from the domain, and these
   rows are unreachable: nothing can start, reset or read them. Their roster
   rows go with them via session_joined_users' ON DELETE CASCADE.

AFTER the drops (so the inserts write the final shape — writing a throwaway
value into a column being dropped in the same migration would be theatre):
3. Give every campaign left without a session a fresh INACTIVE one. This runs
   here rather than lazily at runtime because the new invariant is "exactly one,
   always" — the hero, the drawer and every start path assume it from boot.
4. Enrol each new session's roster from campaign_members, mirroring
   CampaignAggregate.get_all_member_ids(): every role except INVITED.

Downgrade restores the columns (with defaults, so it runs against populated
tables) but deliberately does NOT resurrect the deleted FINISHED rows — they
carried no state any surviving code reads.
"""
import uuid

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9584fb2e1a4c'
down_revision = '7bfb0f207666'
branch_labels = None
depends_on = None


def _move_seat_count_and_drop_finished(connection) -> None:
    """Data step 1-2 — runs while sessions.max_players still exists."""

    # 1. Seat count moves cold: campaign settings, not per-game state.
    connection.execute(sa.text("""
        UPDATE campaigns
        SET max_players = COALESCE((
            SELECT s.max_players
            FROM sessions s
            WHERE s.campaign_id = campaigns.id
              AND s.status <> 'finished'
            ORDER BY s.created_at DESC
            LIMIT 1
        ), 8)
    """))

    # 2. FINISHED rows are unreachable under the new model.
    deleted_finished = connection.execute(
        sa.text("DELETE FROM sessions WHERE status = 'finished'")
    ).rowcount
    print(f"one-session migration: deleted {deleted_finished} finished session(s)")


def _give_every_campaign_a_session(connection) -> None:
    """Data step 3-4 — runs after the drops, so the inserts write the new shape."""

    # 3. Every campaign must own exactly one session. The host is the campaign's
    #    DM, falling back to its creator — the same user in practice, since
    #    CampaignAggregate.create() seats the creator as DM.
    sessionless_campaigns = connection.execute(sa.text("""
        SELECT c.id,
               COALESCE(
                   (SELECT m.user_id FROM campaign_members m
                     WHERE m.campaign_id = c.id AND m.role = 'dm' LIMIT 1),
                   c.created_by
               ) AS host_id
        FROM campaigns c
        WHERE NOT EXISTS (SELECT 1 FROM sessions s WHERE s.campaign_id = c.id)
    """)).fetchall()

    for campaign_id, host_id in sessionless_campaigns:
        session_id = uuid.uuid4()
        connection.execute(
            sa.text("""
                INSERT INTO sessions (id, campaign_id, host_id, status)
                VALUES (:session_id, :campaign_id, :host_id, 'inactive')
            """),
            {"session_id": session_id, "campaign_id": campaign_id, "host_id": host_id},
        )

        # 4. Roster = every campaign member except pending invitees.
        connection.execute(
            sa.text("""
                INSERT INTO session_joined_users (session_id, user_id)
                SELECT :session_id, m.user_id
                FROM campaign_members m
                WHERE m.campaign_id = :campaign_id
                  AND m.role <> 'invited'
            """),
            {"session_id": session_id, "campaign_id": campaign_id},
        )

    print(
        f"one-session migration: created {len(sessionless_campaigns)} replacement session(s)"
    )


def upgrade() -> None:
    connection = op.get_bind()

    op.add_column('campaigns', sa.Column('max_players', sa.Integer(), server_default='8', nullable=False))
    _move_seat_count_and_drop_finished(connection)

    op.drop_column('sessions', 'max_players')
    op.drop_column('sessions', 'name')

    _give_every_campaign_a_session(connection)


def downgrade() -> None:
    # server_default so these run against populated tables; the values are
    # defaults, not the originals, which the upgrade did not preserve.
    op.add_column('sessions', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('sessions', sa.Column('max_players', sa.INTEGER(), server_default='8', autoincrement=False, nullable=False))
    op.drop_column('campaigns', 'max_players')
