"""add granted_by to character_skill_proficiencies

Revision ID: 98a3f6e6f5e4
Revises: fe1642108b90
Create Date: 2026-07-06 09:11:21.106533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '98a3f6e6f5e4'
down_revision = 'fe1642108b90'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_skill_proficiencies', sa.Column('granted_by', sa.String(length=50), server_default='', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('character_skill_proficiencies', 'granted_by')
    # ### end Alembic commands ###