"""add spotify_config to sessions for BGM cross-session persistence

Revision ID: 9bd9515a2d0e
Revises: dd27eba5ec3a
Create Date: 2026-07-07 16:00:14.008675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '9bd9515a2d0e'
down_revision = 'dd27eba5ec3a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('spotify_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'spotify_config')
    # ### end Alembic commands ###