"""add_user_has_received_demo

Revision ID: 9ec4fd5e5a76
Revises: fb17c99ea9f3
Create Date: 2026-01-21 22:26:38.647081

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ec4fd5e5a76'
down_revision = 'fb17c99ea9f3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # Add has_received_demo with server_default for existing users
    # Existing users are assumed to have already received demo (true) to avoid re-creating
    op.add_column('users', sa.Column('has_received_demo', sa.Boolean(), nullable=False, server_default='true'))


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'has_received_demo')
    # ### end Alembic commands ###