"""make_screen_name_nullable

Revision ID: 9ffcc3099a58
Revises: 001
Create Date: 2025-07-15 07:38:17.900564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffcc3099a58'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'screen_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('users', 'auth_method')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('auth_method', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.alter_column('users', 'screen_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###