"""add map_token_state to sessions

Revision ID: a039537eea9f
Revises: c6998dafb35d
Create Date: 2026-07-20 21:26:17.406932

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a039537eea9f'
down_revision = 'c6998dafb35d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('map_token_state', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'map_token_state')
    # ### end Alembic commands ###