"""system-agnostic characters: drop ruleset tables and columns

Revision ID: a0897b4aa764
Revises: af337d62901c
Create Date: 2026-09-12 18:46:52.953906

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a0897b4aa764'
down_revision = 'af337d62901c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_resource_usage')
    op.drop_table('character_save_proficiencies')
    op.drop_table('character_ability_scores')
    op.drop_table('character_subclasses')
    op.drop_table('character_feat_acquisitions')
    op.drop_table('character_spells')
    op.drop_table('character_inventory')
    op.drop_table('character_choices_log')
    op.drop_table('character_skill_proficiencies')
    op.drop_table('character_class_entries')
    op.drop_table('dnd_abilities')
    op.drop_constraint('characters_active_in_campaign_id_fkey', 'characters', type_='foreignkey')
    op.drop_constraint('fk_characters_edition_id', 'characters', type_='foreignkey')
    op.drop_column('characters', 'hp_temp')
    op.drop_column('characters', 'inspiration')
    op.drop_column('characters', 'death_save_successes')
    op.drop_column('characters', 'languages')
    op.drop_column('characters', 'species_code')
    op.drop_column('characters', 'background_code')
    op.drop_column('characters', 'speed')
    op.drop_column('characters', 'xp')
    op.drop_column('characters', 'edition_id')
    op.drop_column('characters', 'creation_step')
    op.drop_column('characters', 'status_effects')
    op.drop_column('characters', 'character_name')
    op.drop_column('characters', 'active_in_campaign_id')
    op.drop_column('characters', 'ac')
    op.drop_column('characters', 'hp_current')
    op.drop_column('characters', 'ability_score_method')
    op.drop_column('characters', 'death_save_failures')
    op.drop_column('characters', 'hp_max')
    op.drop_column('characters', 'level')
    op.drop_column('characters', 'ability_roll_details')
    op.drop_column('characters', 'size')
    op.drop_column('characters', 'currency')
    op.drop_column('characters', 'exhaustion_level')
    op.drop_column('characters', 'species_sub_choices')
    op.drop_column('characters', 'is_draft')
    op.drop_constraint('game_joined_users_selected_character_id_fkey', 'session_joined_users', type_='foreignkey')
    op.drop_column('session_joined_users', 'selected_character_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('session_joined_users', sa.Column('selected_character_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('game_joined_users_selected_character_id_fkey', 'session_joined_users', 'characters', ['selected_character_id'], ['id'], ondelete='SET NULL')
    op.add_column('characters', sa.Column('is_draft', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('species_sub_choices', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('exhaustion_level', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('currency', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('size', sa.VARCHAR(length=10), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('ability_roll_details', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('hp_max', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('death_save_failures', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('ability_score_method', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('hp_current', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('ac', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('active_in_campaign_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('character_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('status_effects', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('creation_step', sa.VARCHAR(length=30), autoincrement=False, nullable=True))
    op.add_column('characters', sa.Column('edition_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('xp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('speed', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('background_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('species_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('languages', postgresql.ARRAY(sa.VARCHAR()), server_default=sa.text("'{}'::character varying[]"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('death_save_successes', sa.SMALLINT(), server_default=sa.text("'0'::smallint"), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('inspiration', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('characters', sa.Column('hp_temp', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_characters_edition_id', 'characters', 'editions', ['edition_id'], ['id'])
    op.create_foreign_key('characters_active_in_campaign_id_fkey', 'characters', 'campaigns', ['active_in_campaign_id'], ['id'], ondelete='SET NULL')
    op.create_table('dnd_abilities',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('dnd_abilities_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='dnd_abilities_pkey'),
    sa.UniqueConstraint('name', name='dnd_abilities_name_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('character_class_entries',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('sub_choices', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), autoincrement=False, nullable=False),
    sa.Column('chosen_skills', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_class_entries_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_class_entries_pkey'),
    sa.UniqueConstraint('character_id', 'class_code', name='uq_character_class')
    )
    op.create_table('character_skill_proficiencies',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('skill_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('expertise', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_skill_proficiencies_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_skill_proficiencies_pkey'),
    sa.UniqueConstraint('character_id', 'skill_code', name='uq_character_skill')
    )
    op.create_table('character_choices_log',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('choice_type', sa.VARCHAR(length=30), autoincrement=False, nullable=False),
    sa.Column('choice_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_choices_log_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_choices_log_pkey')
    )
    op.create_table('character_inventory',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('item_code', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False),
    sa.Column('notes', sa.TEXT(), server_default=sa.text("''::text"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_inventory_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_inventory_pkey')
    )
    op.create_table('character_spells',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('spell_code', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('spell_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('granted_by', sa.VARCHAR(length=50), server_default=sa.text("''::character varying"), autoincrement=False, nullable=False),
    sa.Column('casting_ability', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_spells_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_spells_pkey')
    )
    op.create_table('character_feat_acquisitions',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feat_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('acquired_at_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('source', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_feat_acquisitions_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_feat_acquisitions_pkey'),
    sa.UniqueConstraint('character_id', 'feat_code', 'acquired_at_level', name='uq_character_feat_level')
    )
    op.create_table('character_subclasses',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('class_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('subclass_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('chosen_at_level', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_subclasses_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_subclasses_pkey'),
    sa.UniqueConstraint('character_id', 'class_code', name='uq_character_subclass')
    )
    op.create_table('character_ability_scores',
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('origin_bonus', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['dnd_abilities.id'], name='character_ability_scores_ability_id_fkey'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_ability_scores_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'ability_id', name='character_ability_scores_pkey')
    )
    op.create_table('character_save_proficiencies',
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('ability_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['ability_id'], ['dnd_abilities.id'], name='character_save_proficiencies_ability_id_fkey'),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_save_proficiencies_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('character_id', 'ability_id', name='character_save_proficiencies_pkey')
    )
    op.create_table('character_resource_usage',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('pool_code', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('current_value', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='character_resource_usage_character_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='character_resource_usage_pkey')
    )
    # ### end Alembic commands ###