"""add pc_token_scale to map_assets

Revision ID: a4a712555166
Revises: 363689ff031b
Create Date: 2026-08-19 09:40:42.051422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a712555166'
down_revision = '363689ff031b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_assets', sa.Column('pc_token_scale', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_assets', 'pc_token_scale')
    # ### end Alembic commands ###