"""add news posts likes and reads

Revision ID: a8e1bf630345
Revises: 8996438a78f1
Create Date: 2026-08-31 09:17:29.334653

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a8e1bf630345'
down_revision = '8996438a78f1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_posts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('author_name', sa.String(length=80), nullable=False),
    sa.Column('doc', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('banner_home_top', sa.Text(), nullable=True),
    sa.Column('banner_home_bottom', sa.Text(), nullable=True),
    sa.Column('banner_article_top', sa.Text(), nullable=True),
    sa.Column('banner_article_bottom', sa.Text(), nullable=True),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_news_posts_published_published_at', 'news_posts', ['published', 'published_at'], unique=False)
    op.create_table('news_post_likes',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['news_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_index('ix_news_post_likes_user_id', 'news_post_likes', ['user_id'], unique=False)
    op.create_table('news_post_reads',
    sa.Column('post_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['post_id'], ['news_posts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('post_id', 'user_id')
    )
    op.create_index('ix_news_post_reads_user_id', 'news_post_reads', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_news_post_reads_user_id', table_name='news_post_reads')
    op.drop_table('news_post_reads')
    op.drop_index('ix_news_post_likes_user_id', table_name='news_post_likes')
    op.drop_table('news_post_likes')
    op.drop_index('ix_news_posts_published_published_at', table_name='news_posts')
    op.drop_table('news_posts')
    # ### end Alembic commands ###