"""change grid_cell_size from integer to float

Revision ID: aade28b58b90
Revises: 88c248956ec9
Create Date: 2026-03-29 17:40:48.272323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aade28b58b90'
down_revision = '88c248956ec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_assets', 'grid_cell_size',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('map_assets', 'grid_cell_size',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               existing_nullable=True)
    # ### end Alembic commands ###