"""character config versions and values document (additive)

Revision ID: af337d62901c
Revises: 78e9f165d016
Create Date: 2026-09-12 18:32:49.844167

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af337d62901c'
down_revision = '78e9f165d016'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_config_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('campaign_id', 'version', name='uq_character_config_versions_campaign_version')
    )
    op.create_index(op.f('ix_character_config_versions_campaign_id'), 'character_config_versions', ['campaign_id'], unique=False)
    op.add_column('campaigns', sa.Column('character_config_draft', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    op.add_column('characters', sa.Column('campaign_id', sa.UUID(), nullable=True))
    op.add_column('characters', sa.Column('session_id', sa.UUID(), nullable=True))
    op.add_column('characters', sa.Column('config_version_id', sa.UUID(), nullable=True))
    op.add_column('characters', sa.Column('config_snapshot', postgresql.JSONB(astext_type=sa.Text()), server_default='{"version": 1, "components": []}', nullable=False))
    op.add_column('characters', sa.Column('values', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('characters', sa.Column('display_name', sa.String(length=200), server_default='Unnamed character', nullable=False))
    op.create_index(op.f('ix_characters_campaign_id'), 'characters', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_characters_session_id'), 'characters', ['session_id'], unique=False)
    op.create_index('uq_characters_one_per_party', 'characters', ['session_id', 'user_id'], unique=True, postgresql_where=sa.text('session_id IS NOT NULL AND NOT is_deleted'), sqlite_where=sa.text('session_id IS NOT NULL AND NOT is_deleted'))
    op.create_foreign_key(None, 'characters', 'character_config_versions', ['config_version_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'characters', 'campaigns', ['campaign_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'characters', 'sessions', ['session_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_constraint(None, 'characters', type_='foreignkey')
    op.drop_index('uq_characters_one_per_party', table_name='characters', postgresql_where=sa.text('session_id IS NOT NULL AND NOT is_deleted'), sqlite_where=sa.text('session_id IS NOT NULL AND NOT is_deleted'))
    op.drop_index(op.f('ix_characters_session_id'), table_name='characters')
    op.drop_index(op.f('ix_characters_campaign_id'), table_name='characters')
    op.drop_column('characters', 'display_name')
    op.drop_column('characters', 'values')
    op.drop_column('characters', 'config_snapshot')
    op.drop_column('characters', 'config_version_id')
    op.drop_column('characters', 'session_id')
    op.drop_column('characters', 'campaign_id')
    op.drop_column('campaigns', 'character_config_draft')
    op.drop_index(op.f('ix_character_config_versions_campaign_id'), table_name='character_config_versions')
    op.drop_table('character_config_versions')
    # ### end Alembic commands ###