"""B5 sub-choices: class_entries.sub_choices + characters.species_sub_choices

Revision ID: af8ecd1cc159
Revises: 5d15be3a6c72
Create Date: 2026-06-16 11:52:31.143597

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'af8ecd1cc159'
down_revision = '5d15be3a6c72'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('character_class_entries', sa.Column('sub_choices', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    op.add_column('characters', sa.Column('species_sub_choices', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characters', 'species_sub_choices')
    op.drop_column('character_class_entries', 'sub_choices')
    # ### end Alembic commands ###