"""sessions.scheduled_at

Revision ID: b1ae5a5e538b
Revises: 9584fb2e1a4c
Create Date: 2026-09-06 07:54:28.733723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1ae5a5e538b'
down_revision = '9584fb2e1a4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'scheduled_at')
    # ### end Alembic commands ###