"""add character_subclasses table

Revision ID: beb9ee0c6021
Revises: 7d6ffc78650a
Create Date: 2026-07-05 16:38:38.986968

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'beb9ee0c6021'
down_revision = '7d6ffc78650a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_subclasses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('class_code', sa.String(length=50), nullable=False),
    sa.Column('subclass_code', sa.String(length=50), nullable=False),
    sa.Column('chosen_at_level', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('character_id', 'class_code', name='uq_character_subclass')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_subclasses')
    # ### end Alembic commands ###