# Copyright (C) 2025 Matthew Davey
# SPDX-License-Identifier: GPL-3.0-or-later

"""add_campaign_soft_delete

Revision ID: c3f4e5d6a7b8
Revises: b2e3d8f49c1a
Create Date: 2025-01-15 12:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3f4e5d6a7b8'
down_revision = 'b2e3d8f49c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('campaigns', sa.Column('is_deleted', sa.Boolean(), default=False, nullable=True))
    
    # Set default values for existing records
    op.execute("UPDATE campaigns SET is_deleted = false WHERE is_deleted IS NULL")
    
    # Make is_deleted non-nullable after setting defaults
    op.alter_column('campaigns', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'is_deleted')
    op.drop_column('campaigns', 'deleted_at')
    # ### end Alembic commands ###