"""add grid tuning and colour fields to map_assets

Revision ID: c568ca6b6711
Revises: 6b54f5f634ee
Create Date: 2026-03-19 18:00:06.966079

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c568ca6b6711'
down_revision = '6b54f5f634ee'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('map_assets', sa.Column('grid_margin_x', sa.Integer(), nullable=True))
    op.add_column('map_assets', sa.Column('grid_margin_y', sa.Integer(), nullable=True))
    op.add_column('map_assets', sa.Column('grid_offset_x', sa.Integer(), nullable=True))
    op.add_column('map_assets', sa.Column('grid_offset_y', sa.Integer(), nullable=True))
    op.add_column('map_assets', sa.Column('grid_line_color', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('map_assets', 'grid_line_color')
    op.drop_column('map_assets', 'grid_offset_y')
    op.drop_column('map_assets', 'grid_offset_x')
    op.drop_column('map_assets', 'grid_margin_y')
    op.drop_column('map_assets', 'grid_margin_x')
    # ### end Alembic commands ###