"""add character color and session adventure_log

Revision ID: c6998dafb35d
Revises: e7f05ca5eb4b
Create Date: 2026-07-19 19:41:12.864901

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c6998dafb35d'
down_revision = 'e7f05ca5eb4b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characters', sa.Column('color', sa.String(length=7), nullable=True))
    op.add_column('sessions', sa.Column('adventure_log', postgresql.JSONB(astext_type=sa.Text()), server_default='[]', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'adventure_log')
    op.drop_column('characters', 'color')
    # ### end Alembic commands ###