"""asset tags and favorite

Revision ID: cd10913ed54a
Revises: 8d44e50b786f
Create Date: 2026-07-21 18:01:14.034344

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cd10913ed54a'
down_revision = '8d44e50b786f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_assets', sa.Column('tags', postgresql.ARRAY(sa.String()), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('media_assets', sa.Column('favorite', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index('ix_media_assets_tags', 'media_assets', ['tags'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_media_assets_tags', table_name='media_assets', postgresql_using='gin')
    op.drop_column('media_assets', 'favorite')
    op.drop_column('media_assets', 'tags')
    # ### end Alembic commands ###