"""change_character_lock_from_session_to_campaign

Revision ID: cfde3eb37731
Revises: d3b6ff8f195e
Create Date: 2026-01-28 20:55:52.323195

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cfde3eb37731'
down_revision = 'd3b6ff8f195e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add new campaign lock column
    op.add_column('characters', sa.Column('active_in_campaign_id', sa.UUID(), nullable=True))

    # Drop old session FK constraint (may be named differently based on history)
    op.drop_constraint('characters_active_in_game_id_fkey', 'characters', type_='foreignkey')

    # Create new FK to campaigns table
    op.create_foreign_key(
        'characters_active_in_campaign_id_fkey',
        'characters',
        'campaigns',
        ['active_in_campaign_id'],
        ['id']
    )

    # Drop old session lock column (any existing locks are invalidated by this schema change)
    op.drop_column('characters', 'active_in_session_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###

    # Add back session lock column
    op.add_column('characters', sa.Column('active_in_session_id', sa.UUID(), autoincrement=False, nullable=True))

    # Drop campaign FK
    op.drop_constraint('characters_active_in_campaign_id_fkey', 'characters', type_='foreignkey')

    # Restore session FK
    op.create_foreign_key(
        'characters_active_in_game_id_fkey',
        'characters',
        'sessions',
        ['active_in_session_id'],
        ['id']
    )

    # Drop campaign lock column
    op.drop_column('characters', 'active_in_campaign_id')
    # ### end Alembic commands ###