"""add campaign last_played_at

Revision ID: e58664838aae
Revises: 295bcace5419
Create Date: 2026-08-30 08:49:14.142975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e58664838aae'
down_revision = '295bcace5419'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('campaigns', sa.Column('last_played_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###

    # Backfill from the play history sessions already carry, so existing
    # campaigns don't all read as never played. NULL stays NULL for campaigns
    # whose sessions were never started.
    op.execute(
        """
        UPDATE campaigns
        SET last_played_at = latest.started_at
        FROM (
            SELECT campaign_id, MAX(started_at) AS started_at
            FROM sessions
            WHERE started_at IS NOT NULL
            GROUP BY campaign_id
        ) AS latest
        WHERE campaigns.id = latest.campaign_id
        """
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('campaigns', 'last_played_at')
    # ### end Alembic commands ###