"""add character_spells table

Revision ID: e61ec3b03fc6
Revises: af8ecd1cc159
Create Date: 2026-06-17 08:05:49.663718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e61ec3b03fc6'
down_revision = 'af8ecd1cc159'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('character_spells',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('character_id', sa.UUID(), nullable=False),
    sa.Column('spell_code', sa.String(length=80), nullable=False),
    sa.Column('spell_level', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=20), nullable=False),
    sa.Column('granted_by', sa.String(length=50), server_default='', nullable=False),
    sa.Column('casting_ability', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_spells')
    # ### end Alembic commands ###