"""split audio_assets into music_assets and sfx_assets

Revision ID: e724fd0bd585
Revises: 5db7a22fb5c6
Create Date: 2026-02-19 15:43:23.752646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e724fd0bd585'
down_revision = '5db7a22fb5c6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('music_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('default_volume', sa.Float(), nullable=True),
    sa.Column('default_looping', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sfx_assets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('default_volume', sa.Float(), nullable=True),
    sa.Column('default_looping', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_assets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('audio_assets')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_assets',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('duration_seconds', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('default_volume', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('default_looping', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id'], ['media_assets.id'], name='audio_assets_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='audio_assets_pkey')
    )
    op.drop_table('sfx_assets')
    op.drop_table('music_assets')
    # ### end Alembic commands ###