"""Add urls_expire_at to sessions

Revision ID: e7f05ca5eb4b
Revises: ce2ec30211b3
Create Date: 2026-07-17 09:32:57.544686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7f05ca5eb4b'
down_revision = 'ce2ec30211b3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sessions', sa.Column('urls_expire_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sessions', 'urls_expire_at')
    # ### end Alembic commands ###