"""add cine_config jsonb to image_assets

Revision ID: ef0775587e39
Revises: 24351b802614
Create Date: 2026-03-31 19:44:12.241218

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ef0775587e39'
down_revision = '24351b802614'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('image_assets', sa.Column('cine_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('image_assets', 'cine_config')
    # ### end Alembic commands ###